-- MySQL Script generated by MySQL Workbench
-- Sun Jan  6 13:38:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema payicam_billetterie
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `payicam_billetterie` ;

-- -----------------------------------------------------
-- Schema payicam_billetterie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payicam_billetterie` DEFAULT CHARACTER SET utf8 ;
USE `payicam_billetterie` ;

-- -----------------------------------------------------
-- Table `payicam_billetterie`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`events` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`events` (
  `event_id` INT(11) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `description` TEXT NOT NULL,
  `conditions` TEXT NULL DEFAULT NULL,
  `total_quota` INT(11) NOT NULL,
  `ticketing_start_date` DATETIME NOT NULL,
  `ticketing_end_date` DATETIME NOT NULL,
  `is_active` TINYINT(4) NOT NULL DEFAULT '0',
  `fundation_id` INT(11) NOT NULL,
  `scoobydoo_category_ids` TEXT NOT NULL COMMENT 'Json : {event_cat_id:xxx; promos_cat_id:xxx; options_cat_id:xxx}',
  `created_by` VARCHAR(255) NOT NULL,
  `created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_billetterie`.`promos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`promos` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`promos` (
  `promo_id` INT(11) NOT NULL,
  `promo_name` VARCHAR(45) NOT NULL,
  `still_student` TINYINT(4) NOT NULL DEFAULT '1',
  `has_payicam` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`promo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '										';


-- -----------------------------------------------------
-- Table `payicam_billetterie`.`sites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`sites` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`sites` (
  `site_id` INT(11) NOT NULL,
  `site_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`site_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_billetterie`.`promos_site_specifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`promos_site_specifications` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`promos_site_specifications` (
  `event_id` INT(11) NOT NULL,
  `site_id` INT(11) NOT NULL,
  `promo_id` INT(11) NOT NULL,
  `price` DECIMAL(10,0) NOT NULL,
  `quota` INT(11) NULL DEFAULT NULL,
  `guest_number` INT(11) NOT NULL,
  `scoobydoo_article_id` INT(11) NOT NULL,
  `is_removed` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`event_id`, `site_id`, `promo_id`),
  INDEX `fk_promos_has_sites_sites1_idx` (`site_id` ASC),
  INDEX `fk_promos_has_sites_promos_idx` (`promo_id` ASC),
  INDEX `fk_site_specifications_idx` (`event_id` ASC),
  CONSTRAINT `fk_promos_has_sites_promos`
    FOREIGN KEY (`promo_id`)
    REFERENCES `payicam_billetterie`.`promos` (`promo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promos_has_sites_sites1`
    FOREIGN KEY (`site_id`)
    REFERENCES `payicam_billetterie`.`sites` (`site_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_site_specifications`
    FOREIGN KEY (`event_id`)
    REFERENCES `payicam_billetterie`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_billetterie`.`participants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`participants` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`participants` (
  `participant_id` INT(11) NOT NULL,
  `status` ENUM('A', 'V', 'W') NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `is_icam` TINYINT(4) NOT NULL,
  `price` DECIMAL(10,0) NOT NULL,
  `inscription_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `payement` VARCHAR(45) NOT NULL DEFAULT 'PayIcam',
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `bracelet_identification` VARCHAR(25) NULL DEFAULT NULL,
  `event_id` INT(11) NOT NULL,
  `site_id` INT(11) NOT NULL,
  `promo_id` INT(11) NOT NULL,
  PRIMARY KEY (`participant_id`),
  INDEX `fk_participants_promos_site_specifications1_idx` (`event_id` ASC, `site_id` ASC, `promo_id` ASC),
  CONSTRAINT `fk_participants_promos_site_specifications1`
    FOREIGN KEY (`event_id` , `site_id` , `promo_id`)
    REFERENCES `payicam_billetterie`.`promos_site_specifications` (`event_id` , `site_id` , `promo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_billetterie`.`arrivals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`arrivals` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`arrivals` (
  `arrival_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `participant_id` INT(11) NOT NULL,
  `event_id` INT(11) NOT NULL,
  PRIMARY KEY (`arrival_date`, `participant_id`, `event_id`),
  INDEX `fk_arrivals_participants1_idx` (`participant_id` ASC),
  INDEX `fk_arrivals_events1_idx` (`event_id` ASC),
  CONSTRAINT `fk_arrivals_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `payicam_billetterie`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arrivals_participants1`
    FOREIGN KEY (`participant_id`)
    REFERENCES `payicam_billetterie`.`participants` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_billetterie`.`config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`config` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`config` (
  `folder` VARCHAR(50) NOT NULL DEFAULT '0',
  `is_active` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`folder`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_billetterie`.`icam_has_guests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`icam_has_guests` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`icam_has_guests` (
  `event_id` INT(11) NOT NULL,
  `icam_id` INT(11) NOT NULL,
  `guest_id` INT(11) NOT NULL,
  PRIMARY KEY (`event_id`, `icam_id`, `guest_id`),
  INDEX `fk_participants_has_participants_participants2_idx` (`guest_id` ASC),
  INDEX `fk_participants_has_participants_participants1_idx` (`icam_id` ASC),
  INDEX `fk_icam_has_guests_events1_idx` (`event_id` ASC),
  CONSTRAINT `fk_icam_has_guests_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `payicam_billetterie`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participants_has_participants_participants1`
    FOREIGN KEY (`icam_id`)
    REFERENCES `payicam_billetterie`.`participants` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participants_has_participants_participants2`
    FOREIGN KEY (`guest_id`)
    REFERENCES `payicam_billetterie`.`participants` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_billetterie`.`options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`options` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`options` (
  `option_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '0',
  `is_mandatory` TINYINT(1) NOT NULL DEFAULT '0',
  `type` VARCHAR(45) NOT NULL,
  `quota` INT(11) NULL DEFAULT NULL,
  `is_removed` TINYINT(1) NOT NULL DEFAULT '0',
  `event_id` INT(11) NOT NULL,
  PRIMARY KEY (`option_id`),
  INDEX `fk_options_events1_idx` (`event_id` ASC),
  CONSTRAINT `fk_options_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `payicam_billetterie`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_billetterie`.`option_choices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`option_choices` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`option_choices` (
  `choice_id` INT(11) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `scoobydoo_article_id` INT(11) NOT NULL,
  `is_removed` TINYINT(1) NOT NULL DEFAULT '0',
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `quota` VARCHAR(45) NULL DEFAULT NULL,
  `option_id` INT(11) NOT NULL,
  PRIMARY KEY (`choice_id`),
  INDEX `fk_option_choices_options1_idx` (`option_id` ASC),
  CONSTRAINT `fk_option_choices_options1`
    FOREIGN KEY (`option_id`)
    REFERENCES `payicam_billetterie`.`options` (`option_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_billetterie`.`participant_has_options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`participant_has_options` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`participant_has_options` (
  `event_id` INT(11) NOT NULL,
  `participant_id` INT(11) NOT NULL,
  `choice_id` INT(11) NOT NULL,
  `status` ENUM('A', 'V', 'W') NOT NULL,
  `option_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `price` INT(11) NOT NULL,
  `payement` VARCHAR(45) NOT NULL DEFAULT 'PayIcam',
  PRIMARY KEY (`event_id`, `participant_id`, `choice_id`),
  INDEX `fk_participants_has_options_participants1_idx` (`participant_id` ASC),
  INDEX `fk_participants_has_options_events1_idx` (`event_id` ASC),
  INDEX `fk_participant_has_options_option_choices1_idx` (`choice_id` ASC),
  CONSTRAINT `fk_participant_has_options_option_choices1`
    FOREIGN KEY (`choice_id`)
    REFERENCES `payicam_billetterie`.`option_choices` (`choice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participants_has_options_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `payicam_billetterie`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participants_has_options_participants1`
    FOREIGN KEY (`participant_id`)
    REFERENCES `payicam_billetterie`.`participants` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_billetterie`.`promo_site_has_options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`promo_site_has_options` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`promo_site_has_options` (
  `event_id` INT(11) NOT NULL,
  `site_id` INT(11) NOT NULL,
  `promo_id` INT(11) NOT NULL,
  `option_id` INT(11) NOT NULL,
  PRIMARY KEY (`event_id`, `site_id`, `promo_id`, `option_id`),
  INDEX `fk_promos_site_specifications_has_options_options1_idx` (`option_id` ASC),
  INDEX `fk_promos_site_specifications_has_options_promos_site_speci_idx` (`event_id` ASC, `site_id` ASC, `promo_id` ASC),
  CONSTRAINT `fk_promos_site_specifications_has_options_options1`
    FOREIGN KEY (`option_id`)
    REFERENCES `payicam_billetterie`.`options` (`option_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promos_site_specifications_has_options_promos_site_specifi1`
    FOREIGN KEY (`event_id` , `site_id` , `promo_id`)
    REFERENCES `payicam_billetterie`.`promos_site_specifications` (`event_id` , `site_id` , `promo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_billetterie`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_billetterie`.`transactions` ;

CREATE TABLE IF NOT EXISTS `payicam_billetterie`.`transactions` (
  `transaction_id` INT(11) NOT NULL,
  `status` ENUM('A', 'V', 'W') NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `liste_places_options` TEXT NOT NULL COMMENT '{places:{participant_id}, options{participant_id, option_id}}',
  `price` DECIMAL(10,0) NOT NULL,
  `date_demande` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_payement` DATETIME NULL DEFAULT NULL,
  `payicam_transaction_id` INT(11) NOT NULL,
  `payicam_transaction_url` TEXT NOT NULL,
  `event_id` INT(11) NOT NULL,
  `icam_id` INT(11) NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `fk_transactions_events1_idx` (`event_id` ASC),
  INDEX `fk_transactions_participants1_idx` (`icam_id` ASC),
  CONSTRAINT `fk_transactions_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `payicam_billetterie`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_participants1`
    FOREIGN KEY (`icam_id`)
    REFERENCES `payicam_billetterie`.`participants` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `payicam_billetterie`.`promos`
-- -----------------------------------------------------
START TRANSACTION;
USE `payicam_billetterie`;
INSERT INTO `payicam_billetterie`.`promos` (`promo_id`, `promo_name`, `still_student`, `has_payicam`) VALUES
    (1, '115', 0, 1),
    (2, '114', 0, 1),
    (3, '115', 0, 1),
    (4, '116', 0, 1),
    (5, '117', 0, 1),
    (6, '118', 0, 1),
    (7, '2015', 0, 1),
    (8, '2016', 0, 1),
    (9, '2017', 0, 1),
    (10, '2018', 0, 1),
    (11, '119', 1, 1),
    (12, '2019', 1, 1),
    (13, '120', 1, 1),
    (14, '2020', 1, 1),
    (15, '121', 1, 1),
    (16, '2021', 1, 1),
    (17, '122', 1, 1),
    (18, '2022', 1, 1),
    (19, '123', 1, 1),
    (20, '2023', 1, 1),
    (21, '24', 1, 1),
    (100, 'Ingénieurs', 0, 0),
    (101, 'Invités', 2, 1),
    (102, 'Permanents', 2, 1),
    (103, 'Artistes', 2, 0),
    (104, 'Autre', 2, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `payicam_billetterie`.`sites`
-- -----------------------------------------------------
START TRANSACTION;
USE `payicam_billetterie`;
INSERT INTO `payicam_billetterie`.`sites` (`site_id`, `site_name`) VALUES
    (1, 'Lille'),
    (2, 'Toulouse');

COMMIT;


-- -----------------------------------------------------
-- Data for table `payicam_billetterie`.`config`
-- -----------------------------------------------------
START TRANSACTION;
USE `payicam_billetterie`;
INSERT INTO `payicam_billetterie`.`config` (`folder`, `is_active`) VALUES
    ('event_administration', 1),
    ('inscriptions', 1),
    ('participant_administration', 1),
    ('ticketing', 1);

COMMIT;

